FROM node:22

WORKDIR /app

# Copiar package.json y package-lock.json
COPY package.json package-lock.json* ./

# Forzar instalación de todo (dev + optional deps)
RUN npm install --legacy-peer-deps

# Copiar el resto del proyecto
COPY . .

# Exponer puerto de Vite
EXPOSE 5173

# Levantar Vite
CMD ["npx", "vite", "--host", "0.0.0.0"]
