version: "3.9"
services:
  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./BACKEND
    container_name: backend_app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/reservas_gym
    depends_on:
      - mongo
    volumes:
      - ./BACKEND:/app

  frontend:
    build: ./FRONTEND
    container_name: frontend_app
    ports:
      - "3000:5173"
    depends_on:
      - backend
    volumes:
      - ./FRONTEND:/app
      - /app/node_modules

volumes:
  mongo_data:
